function call_sep_scatter_bar_plot()

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'N33Cc'},'arm',{'un'},'post',{'post1'},'cohort',{'6sess'},'glove',{'-g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'P25Cc_N33Cc'},'arm',{'inv'},'post',{'post2'},'cohort',{'6sess'},'glove',{'-g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'P45Cc_N60Cc'},'arm',{'un'},'post',{'post2'},'cohort',{'6sess'},'glove',{'+g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'P100Cc'},'arm',{'un'},'post',{'post2'},'cohort',{'6sess'},'glove',{'+g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'P25Cc_N33Cc'},'arm',{'inv'},'post',{'post2'},'cohort',{'whole'},'glove',{'+/-g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'P45Cc_N60Cc'},'arm',{'un'},'post',{'post1'},'cohort',{'6sess'},'glove',{'-g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'N120Cc'},'arm',{'un'},'post',{'post2'},'cohort',{'6sess'},'glove',{'-g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'N120Cc'},'arm',{'un'},'post',{'post2'},'cohort',{'6sess'},'glove',{'-g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'N33Cc_P45Cc'},'arm',{'inv'},'post',{'post2'},'cohort',{'6sess'},'glove',{'-g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'N33Cc_P45Cc'},'arm',{'inv'},'post',{'post1'},'cohort',{'6sess'},'glove',{'+g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'P45Cc'},'arm',{'un'},'post',{'post2'},'cohort',{'whole'},'glove',{'+g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'P100Cc'},'arm',{'un'},'post',{'post2'},'cohort',{'whole'},'glove',{'+g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'P45Cc_N60Cc'},'arm',{'un'},'post',{'post1'},'cohort',{'6sess'},'glove',{'-g'});

sep_scatter_bar_plot('file','sep_data_format_pre_post_diff.xlsx', ...
	'measures',{'N33Cc'},'arm',{'un'},'post',{'post1'},'cohort',{'whole'},'glove',{'+g'});
